@startuml
!pragma teoz
!include ..\iuml\common.iuml
'!include ..\iuml\sequence.iuml
!include ..\iuml\scripts.iuml

title " "

a -> b ++

note left: $diagramFileName

$qnote("где задается боковое ускорение?",$wrapWidth=10)
$exec(b,asdf ;lksdaf lorem ipsum asdf  asd f asdf)

note left : $wrap("asdf ;lksdaf lorem ipsum asdf  asd f asdf",15)

note right: %call_user_func("$wrap", "asdf ;lksdaf lorem ipsum asdf  asd f asdf" ,15)


@enduml

