@startuml
!pragma teoz
!include ..\iuml\common.iuml
'!include ..\iuml\sequence.iuml
!include ..\iuml\scripts.iuml

title " "

a -> b ++

note left: $diagramFileName

$qnote("где задается боковое ускорение?",$wrapWidth=10)
$exec(b,asdf ;lksdaf lorem ipsum asdf  asd f asdf)

note left : $wrap("asdf ;lksdaf lorem ipsum asdf  asd f asdf",15)

note right: %call_user_func("$wrap", "asdf ;lksdaf lorem ipsum asdf  asd f asdf" ,15)

                        $todo(b,"getVehicleCANParameter(vehicleID,dao,Collections.singletonList(new Long[]{0L,intervals.get(0)[0]}),coef.dependOn.name(),params.getStatLogToken())",$wrapWidth=50)


@enduml

