@startuml
'https://plantuml.com/sequence-diagram

!include ..\iuml\scripts.iuml

$makeLegend("asdf#green;lczod#red")

autonumber

Alice -> Bob: Authentication Request
Bob --> Alice: Authentication Response

Alice -> Bob: Another authentication Request
Alice <-- Bob: another authentication Response
@enduml