@startuml

!include ..\iuml\reading.iuml


:he:  $male_protagonist

:she: <<todo>> $female_protagonist

he --> she : special one

someone <<todo>> $male
otherone $female

(institution) <<institution>>
(event) <<event>><<todo>>
(location) <<location>>
(group) <<group>>

someone -- (institution)
(institution) - he
someone -- (event)
he - (event)

(location) -- otherone
group -- otherone

(location) - she
she - group


@enduml