

skinparam maxmessagesize 120
skinparam swimlanebordercolor #steelblue
skinparam swimlanetitlefontcolor #steelblue

skinparam activitystartcolor #maroon
skinparam activitystopcolor #maroon
skinparam activityendcolor #maroon

skinparam shadowing false

skinparam arrowfontcolor #orangered
skinparam defaultfontsize 16
skinparam arrowfontsize 14
skinparam partitionbackgroundcolor #6F8F6F30

skinparam partitionfontsize 18
skinparam partitionfontcolor coral

skinparam wrapwidth 260