skin rose

scale max 4096*4096


skinparam defaultfontcolor #brown
skinparam backgroundcolor transparent
skinparam arrowfontcolor #0F8C29
skinparam wrapwidth 180
skinparam titlefontcolor dodgerblue

skinparam note<<q>>backgroundcolor lightsalmon
skinparam note<<q>>fontcolor navy

<style>
element {
  MaximumWidth 180
}
note {
  MaximumWidth 200
  .wide {
    MaximumWidth 500
  }
}
</style>



!$diagramFileName = %splitstr(%filename(),'.')
!if %size($diagramFileName) > 0
    !$titleString = $diagramFileName[0]

    !if %size($diagramFileName) == 3
        !$titleString = $titleString + " " + $diagramFileName[1] + " diagram"
    !endif
    title $titleString
!endif
