<style>
    jsondiagram {
        backgroundcolor transparent
        node {
            linecolor forestgreen
            backgroundcolor darkgray
            fontcolor blue
        }
        arrow{
            linecolor steelblue
            linethickness 4
        }
    }
</style>

