<style>
    jsondiagram {
        backgroundcolor transparent
        node {
            linecolor forestgreen
            backgroundcolor silver
            fontcolor blue
        }
        arrow{
            linecolor steelblue
        }

    }
</style>
