<style>
    jsondiagram {
        backgroundcolor transparent
        node {
            linecolor forestgreen
            backgroundcolor gray
            fontcolor navy
        }
        arrow{
            linecolor steelblue
        }

    }
</style>
