skin rose
skinparam backgroundcolor seashell
skinparam wrapwidth 100
left to right direction

skinparam usecase<<event>>usecasebackgroundcolor technology
skinparam usecase<<location>>usecasebackgroundcolor lavender
skinparam usecase<<institution>>usecasebackgroundcolor strategy
skinparam usecase<<group>>backgroundcolor implementation

skinparam actor<<protagonist>>backgroundcolor pink
