skin rose
skinparam backgroundcolor transparent
skinparam defaultfontcolor steelblue
skinparam wrapwidth 100
skinparam maxmessagesize 100
left to right direction

!$male="#forestgreen"
!$male_protagonist="<<protagonist>> #lime"
!$female="#darkgoldenrod"
!$female_protagonist="<<protagonist>> #yellow"

skinparam usecase<<event>>backgroundcolor technology
skinparam usecase<<location>>backgroundcolor lavender
skinparam usecase<<institution>>backgroundcolor strategy
skinparam usecase<<group>>backgroundcolor implementation
skinparam usecase<<project>>backgroundcolor pink

skinparam actor<<dead>>bordercolor gray
skinparam actor<<dead>>shadowing false

skinparam actor<<unnamed>>fontcolor forestgreen
skinparam actor<<unnamed>>fontstyle italic
skinparam actor<<unnamed>>fontname times new roman

skinparam actor<<todo>>fontstyle bold
skinparam actor<<todo>>fontcolor red

skinparam usecase<<todo>>fontstyle bold
skinparam usecase<<todo>>fontcolor red

skinparam actor<<mentioned>>borderstyle dotted

skinparam package<<current>>backgroundcolor technology

skinparam actor<<alias>>bordercolor teal

<style>
.exarrow {
  linecolor green
  fontcolor green
  linestyle 3
  linethickness 0.5
}
</style>

!$ex = "<<exarrow>> : <<ex>>"