skin rose
skinparam backgroundcolor transparent
skinparam defaultfontcolor steelblue
skinparam wrapwidth 100
skinparam maxmessagesize 80
left to right direction

!$male="#forestgreen"
!$male_protagonist="#lime"
!$female="#darkgoldenrod"
!$female_protagonist="#yellow"

skinparam usecase<<event>>backgroundcolor technology
skinparam usecase<<location>>backgroundcolor lavender
skinparam usecase<<institution>>backgroundcolor strategy
skinparam usecase<<group>>backgroundcolor implementation

