skinparam SequenceGroupBodyBackgroundColor #5F7FaF60
skinparam sequencegroupbordercolor #8f8f8f
skinparam sequencegroupborderthickness .5
skinparam defaultfontcolor forestgreen
skinparam maxmessagesize 600
skinparam responsemessagebelowarrow true
skinparam sequencereferencebackgroundcolor application
skinparam sequencebreakgroupbodybackgroundcolor #red
hide footbox
hide unlinked

!pragma teoz true
