skinparam SequenceGroupBodyBackgroundColor #5F7FaF10
skinparam sequencegroupbordercolor #4f4f4f
skinparam sequencegroupborderthickness .5
skinparam defaultfontcolor forestgreen
skinparam maxmessagesize 600
skinparam responsemessagebelowarrow true
skinparam sequencereferencebackgroundcolor application
skinparam sequencebreakgroupbodybackgroundcolor #red
hide footbox
hide unlinked

<style>
note {
  MaximumWidth 180
  .wide {
    MaximumWidth 500
  }
}
</style>
